### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by echo465** [TL/gmailJack#1]
The app doesn't seem to work properly.  I'm getting the following output on the console:

```
 is not using Google Apps!
 is not using Google Apps!
 is not using Google Apps!et
 is not using Google Apps!
 is not using Google Apps!om
 is not using Google Apps!
```

So, it maybe isn't reading the domains passed to it?  I'm really not sure what's going on here.  It also never outputs anything into an output file, and I've tested this by putting a domain in the list that does have google apps attached.

**Comment by echo465** [comment]
Hmm.
```
 is not using Google Apps!
 is not using Google Apps!1internationalindependentescorts-1932.com
 is not using Google Apps!
```

```
bn01:~/gmailJack# cat domains.txt | grep nternationalindependentescorts
worldno1escortsagencies-no1internationalindependentescorts-1932.com
bn01:~/gmailJack#
```

(man, how could they let THAT one get away....)  Ok, so it's overwriting the domain name with the status message?  Ok, no big deal, but the bigger problem is that it never writes anything to the output file.

**Comment by TL** [comment]
RS1119:gmailJack thomasleamy$ ./gmailJack.sh domainlist.txt output.txt
Scanning list for Google Apps enabled domains...
hello.com is using Google Apps!
this.com is not using Google Apps!
is.com is not using Google Apps!
atest.com is not using Google Apps!
idsjosdfi.com is not using Google Apps!
thisshouldnotbeassociated.com is not using Google Apps!
Output file saved. Finished.

RS1119:gmailJack thomasleamy$ cat output.txt 
hello.com

-----------

It should only output the domains that are associated with Google hosted mail accounts, so you that you can put them in for bulk registration.

I'm running this on my Mac by the way.

**Comment by echo465** [comment]
Strange, that is working for me.  Maybe my input file is messed up
somehow.  Thanks for looking.

**Comment by echo465** [comment]
Appears that the issue was the input file.  I ran it through dos2unix, and it worked like a champ.
